max_width = 110
array_width = 75
attr_fn_like_width = 70
chain_width = 75
comment_width = 80
doc_comment_code_block_width = 80
fn_call_width = 75
single_line_let_else_max_width = 0
struct_lit_width = 50
struct_variant_width = 50
use_small_heuristics = "Default"

format_code_in_doc_comments = true

hex_literal_case = "Upper"

group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"

combine_control_expr = false
match_block_trailing_comma = true
overflow_delimited_expr = true
use_field_init_shorthand = true
